# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Thriving Stones' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thriving Stones
  pod 'Firebase/Core'

  pod 'Firebase/Messaging'

  pod 'Firebase/Database'

  pod 'Firebase/Storage'

  pod 'Firebase/Auth'

  pod 'CBZSplashView', '~> 1.0.0'

end
